project:
  type: website

website:
  title: "E155 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: lab1.qmd
        text: Lab 1
      - href: lab2.qmd
        text: Lab 2
     

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



